Typo fixes and re-formatting etc.
SPAAM-community/intro-to-ancient-metagenomics-book pull request #17
Opened 2023-07-04 14:11 UTC by jfy133

2023-07-05 09:55 UTC, TCLamnidis requested changes
BBB edits LGTM, but dark mode is broken. Changes the colour of text but not the background.

2023-07-05 09:55 UTC, TCLamnidis commented on bare-bones-bash.qmd
> +![Diagram showing stdin going into the program, and two output streams from the program: stderr and stdout](assets/images/chapters/bare-bones-bash/Datastreams.png){#fig-Datastreams width=80% fig-alig
```suggestion
![Diagram showing stdin going into the program, and two output streams from the program: stderr and stdout.](assets/images/chapters/bare-bones-bash/Datastreams.png){#fig-Datastreams width=80% fig-align="center"}
```

2023-07-05 09:55 UTC, TCLamnidis commented on bare-bones-bash.qmd
> +![This program in the form of a bash script executed in the terminal takes no input, and prints one line to the stdout and one line to the stderr.](assets/images/chapters/bare-bones-bash/Datastream_s
```suggestion
![This program (in the form of a bash script executed in the terminal) takes no input, and prints one line to the stdout and one line to the stderr.](assets/images/chapters/bare-bones-bash/Datastream_showcase.png){#fig-Datastream_showcase width=100%}
```

2023-07-05 09:55 UTC, TCLamnidis commented on bare-bones-bash.qmd
> +![Diagram showing stdin going into the program, and two output streams from the program: stderr and stdout, with the stdout being attached to the stdin of a second program](assets/images/chapters/bar
```suggestion
![Diagram showing stdin going into the program, and two output streams from the program: stderr and stdout, with the stdout becoming the stdin of a second program.](assets/images/chapters/bare-bones-bash/Piping.png){#fig-Piping width=80% fig-align="center"}
```

2023-07-05 11:40 UTC, TCLamnidis commented
The font colour of non-language specific monospace blocks is different between dark and light mode. Since the block has consistent background, I am not sure that is necessary. Maybe both could be a midway between the two colours (#666666 ?) instead.

Also, for some reason swapping between dark/light mode seems to change the new line breaks. This happens both in the sidebar title, but also the text (where it matters less).

2023-07-05 11:47 UTC, TCLamnidis commented
Also, I noticed that the portraits of the three authors need updating for darkmode. The white parts of the PNGs are actually transparent, making the dark mode images scarring 😅 . Cannot do that on my end, but someone more skilled with illustrator/Inkscape (@aidaanva) might be able to?

2023-07-06 09:10 UTC, aidaanva commented
I can work on it on friday

2023-07-10 13:12 UTC, merged

2023-07-10 13:12 UTC, jfy133 commented
Feel free to make a new PR if you see anything else cropping up